sonar.projectKey=khw315_calendarr
sonar.organization=khw315
sonar.sourceEncoding=UTF-8
sonar.defaultBaseBranch=main

# Go Coverage & Test Configuration
sonar.go.coverage.reportPaths=coverage.out
sonar.sources=.
sonar.exclusions=main.go,**/*_test.go,**/vendor/**,logs/**,frontend/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
